### ISSUE TITLE
mnist download command downloading fashion.

### ISSUE THREAD

**Issue by Ujjawal-K-Panchal** [Ujjawal-K-Panchal/coshnet#7]
Even when we pass `--dataset mnist` to `test_fashion.py`, the initial download downloads the Fashion MNIST dataset and downloads it within MNIST directory. This is because, [load_fashion()](https://github.com/Ujjawal-K-Panchal/coshnet/blob/c884494ca50b19db23dbcc08a6b4d31f7980e418/libs/shnetutil/shnetutil/dataset/fashion.py#L26) function is not passing `kFashion` parameter to [getdb()](https://github.com/Ujjawal-K-Panchal/coshnet/blob/c884494ca50b19db23dbcc08a6b4d31f7980e418/libs/shnetutil/shnetutil/pipeline/loadMNIST.py#L235) function. This is causing `kFashion` to default to true and for the URL fetched for downloading the dataset to be `Fashion MNIST` url even if the user wished for `MNIST` url.

**Comment by mannykao** [comment]
good catch.
